import { User } from '../interfaces/user';

export const USER_INFO: User[] = [
  {
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    password: 'P@ssw0rd1!',
    phone: '+1-555-0101',
    city: 'New York',
    country: 'USA',
  },
  {
    name: 'Bob Smith',
    email: 'bob.s@example.com',
    password: 'S3cur3P@ss',
    phone: '+44-555-0102',
    city: 'London',
    country: 'UK',
  },
  {
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    password: 'MyP@ss123',
    phone: '+33-555-0103',
    city: 'Paris',
    country: 'France',
  },
  {
    name: 'Diana Prince',
    email: 'diana.p@example.com',
    password: 'W0nderW0man',
    phone: '+49-555-0104',
    city: 'Berlin',
    country: 'Germany',
  },
  {
    name: 'Evan Wright',
    email: 'evan.w@example.com',
    password: 'Ev@n2024!',
    phone: '+81-555-0105',
    city: 'Tokyo',
    country: 'Japan',
  },
  {
    name: 'Fiona Gallagher',
    email: 'fiona.g@example.com',
    password: 'F10n@Pass',
    phone: '+61-555-0106',
    city: 'Sydney',
    country: 'Australia',
  },
  {
    name: 'George Miller',
    email: 'george.m@example.com',
    password: 'G30rg3#Pass',
    phone: '+1-555-0107',
    city: 'Toronto',
    country: 'Canada',
  },
  {
    name: 'Hannah Abbott',
    email: 'hannah.a@example.com',
    password: 'H@nn@h99',
    phone: '+34-555-0108',
    city: 'Madrid',
    country: 'Spain',
  },
  {
    name: 'Ian Curtis',
    email: 'ian.c@example.com',
    password: 'I@nCurt1s',
    phone: '+39-555-0109',
    city: 'Rome',
    country: 'Italy',
  },
  {
    name: 'Julia Roberts',
    email: 'julia.r@example.com',
    password: 'Jul1@R0b3rts',
    phone: '+55-555-0110',
    city: 'Sao Paulo',
    country: 'Brazil',
  },
  {
    name: 'Kevin Hart',
    email: 'kevin.h@example.com',
    password: 'K3v1nH@rt',
    phone: '+82-555-0111',
    city: 'Seoul',
    country: 'South Korea',
  },
  {
    name: 'Laura Palmer',
    email: 'laura.p@example.com',
    password: 'L@ur@P@lm',
    phone: '+7-555-0112',
    city: 'Moscow',
    country: 'Russia',
  },
  {
    name: 'Michael Scott',
    email: 'michael.s@example.com',
    password: 'Th@tW@htS@id',
    phone: '+1-555-0113',
    city: 'Chicago',
    country: 'USA',
  },
  {
    name: 'Nina Simone',
    email: 'nina.s@example.com',
    password: 'N1n@S1m0ne',
    phone: '+27-555-0114',
    city: 'Cape Town',
    country: 'South Africa',
  },
  {
    name: 'Oscar Isaac',
    email: 'oscar.i@example.com',
    password: '0sc@r1s@@c',
    phone: '+52-555-0115',
    city: 'Mexico City',
    country: 'Mexico',
  },
  {
    name: 'Paula Abdul',
    email: 'paula.a@example.com',
    password: 'P@ul@Abdul',
    phone: '+91-555-0116',
    city: 'Mumbai',
    country: 'India',
  },
  {
    name: 'Quinn Hughes',
    email: 'quinn.h@example.com',
    password: 'Qu1nnHugh3s',
    phone: '+1-555-0117',
    city: 'Vancouver',
    country: 'Canada',
  },
  {
    name: 'Ryan Reynolds',
    email: 'ryan.r@example.com',
    password: 'D3@dP00l1',
    phone: '+64-555-0118',
    city: 'Auckland',
    country: 'New Zealand',
  },
  {
    name: 'Sarah Connor',
    email: 'sarah.c@example.com',
    password: 'T3rm1n@t0r',
    phone: '+86-555-0119',
    city: 'Beijing',
    country: 'China',
  },
  {
    name: 'Tom Hiddleston',
    email: 'tom.h@example.com',
    password: 'L0k1Od1ns0n',
    phone: '+46-555-0120',
    city: 'Stockholm',
    country: 'Sweden',
  },
];
